In [1]:
import torch

In [2]:
torch.__version__

'2.3.1+cu118'

In [3]:
# Check if a GPU is available
if torch.cuda.is_available():
  print("A GPU is available!")
else:
  print("No GPU available.")

# Get the name of the GPU
device = torch.cuda.get_device_name(0)
print(f"The GPU name is: {device}")

A GPU is available!
The GPU name is: NVIDIA GeForce GTX 1060


### Creating tensors

In [4]:
torch.cuda.is_available()

True

In [5]:
# scalar(rank 0 tensor)
scalar = torch.tensor(10)
scalar

tensor(10)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()

10

In [8]:
# Vector(rank 1 tensor)
vector = torch.tensor([16, 19])
vector

tensor([16, 19])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix(tensor of rank 2)
Matrix = torch.tensor([[16, 2],
                       [19, 11]])
Matrix

tensor([[16,  2],
        [19, 11]])

In [12]:
Matrix.ndim

2

In [13]:
Matrix[0]

tensor([16,  2])

In [14]:
Matrix[1]

tensor([19, 11])

In [15]:
Matrix.shape

torch.Size([2, 2])

In [16]:
# rank 3 tensor
Tensor_3 = torch.tensor([[[1, 6, 12],
                          [1, 9, 12],
                          [2, 3, 8]]])

In [17]:
Tensor_3

tensor([[[ 1,  6, 12],
         [ 1,  9, 12],
         [ 2,  3,  8]]])

In [18]:
Tensor_3.ndim

3

In [19]:
Tensor_3.shape

torch.Size([1, 3, 3])

### Random tensors

In [20]:
# Creating a random tensor of size(4, 2)
random_tensor = torch.rand(4, 2)

In [21]:
random_tensor

tensor([[0.6837, 0.6043],
        [0.0494, 0.6651],
        [0.8790, 0.1079],
        [0.0704, 0.2870]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor.shape

torch.Size([4, 2])

In [24]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(3, 64, 64))

In [25]:
random_image_tensor.shape

torch.Size([3, 64, 64])

In [26]:
random_image_tensor.ndim

3

In [27]:
# Creating a tensor of zeros
zeros = torch.zeros(size=(4, 2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [28]:
# Hadamard product of matrices
zeros * random_tensor

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [29]:
# Create a tensor of all ones
ones = torch.ones(size=(4, 2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [30]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [31]:
torch.range(0, 10)

C:\Users\user\AppData\Local\Temp\ipykernel_1976\1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
torch.arange(2, 9)

tensor([2, 3, 4, 5, 6, 7, 8])

In [33]:
tensor_7 = torch.arange(start=1, end=20, step=3)
tensor_7

tensor([ 1,  4,  7, 10, 13, 16, 19])

In [34]:
seven_zeros = torch.zeros_like(input=tensor_7)
seven_zeros

tensor([0, 0, 0, 0, 0, 0, 0])

In [35]:
seven_ones = torch.ones_like(input=tensor_7)
seven_ones

tensor([1, 1, 1, 1, 1, 1, 1])

In [36]:
float_32_tensor = torch.tensor([1,6,2],
                               dtype=torch.float32,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([1., 6., 2.])

In [37]:
float_32_tensor.dtype

torch.float32

In [38]:
float_32_tensor.device

device(type='cpu')

In [39]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [40]:
float_16_tensor

tensor([1., 6., 2.], dtype=torch.float16)

In [41]:
float_32_tensor * float_16_tensor

tensor([ 1., 36.,  4.])

In [42]:
int_32_tensor = torch.tensor([1, 9, 11], dtype=torch.int32)
int_32_tensor

tensor([ 1,  9, 11], dtype=torch.int32)

In [43]:
float_32_tensor * int_32_tensor

tensor([ 1., 54., 22.])

In [44]:
pb_tensor = torch.rand(3, 4)

In [45]:
pb_tensor

tensor([[0.7033, 0.0712, 0.9935, 0.7618],
        [0.9490, 0.3087, 0.5206, 0.6473],
        [0.0959, 0.5666, 0.6761, 0.7652]])

In [46]:
print(f"datatype of tensor: {pb_tensor.dtype}")
print(f"shape of tensor: {pb_tensor.shape}")
print(f"device of tensor: {pb_tensor.device}")

datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device of tensor: cpu


### Tensor Operations
* Addition
* Substraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [47]:
tensor = torch.tensor([1, 6, 2])

In [48]:
tensor + 10

tensor([11, 16, 12])

In [49]:
tensor*10

tensor([10, 60, 20])

In [50]:
tensor - 10

tensor([-9, -4, -8])

In [51]:
torch.mul(tensor, 100)

tensor([100, 600, 200])

In [52]:
torch.add(tensor, 10)

tensor([11, 16, 12])

### Matrix multiplication
1. Element wise operation
2. Matrix multiplication

In [53]:
# Element wise multiplication
print(tensor, '*', tensor, f"equals: {tensor * tensor}")

tensor([1, 6, 2]) * tensor([1, 6, 2]) equals: tensor([ 1, 36,  4])


In [54]:
# Matrix multilication(here a dotproduct between the vector)
torch.matmul(tensor, tensor)

tensor(41)

In [55]:
%%time
dotproduct = 0
for k in range(len(tensor)):
    dotproduct += tensor[k] * tensor[k]
dotproduct

CPU times: total: 0 ns
Wall time: 7.45 ms


tensor(41)

In [56]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(41)

In [57]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 4))

tensor([[0.4898, 0.0570, 0.5488, 0.0281],
        [0.2768, 0.3831, 0.6291, 0.1837],
        [0.1208, 0.1424, 0.2521, 0.0683]])

### Transpose of a matrix

In [58]:
tensor_k = torch.tensor([[1, 6],
                         [1, 9],
                         [2, 11]])
tensor_k

tensor([[ 1,  6],
        [ 1,  9],
        [ 2, 11]])

In [59]:
tensor_k.T

tensor([[ 1,  1,  2],
        [ 6,  9, 11]])

### Finding the minimum, maximum, mean, sum etc(tensor aggregation)

In [60]:
S = torch.arange(0, 100, 10)
S

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
# Find the min
torch.min(S), S.min()

(tensor(0), tensor(0))

In [62]:
# Find the max
torch.max(S), S.max()

(tensor(90), tensor(90))

In [63]:
# Find the mean
torch.mean(S)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [64]:
torch.mean(S.type(torch.float32)), S.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [65]:
# Find the sum
torch.sum(S), S.sum()

(tensor(450), tensor(450))

### Finding the positional minimum and maximum

In [66]:
S1 = torch.arange(1, 100, 10)
S1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [67]:
S1.argmin()

tensor(0)

In [68]:
S1.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

In [69]:
S2 = torch.arange(1., 10.)

In [70]:
S2.reshape(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [71]:
S2.reshape(9, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [72]:
z  = S2.view(1, 9)

In [73]:
S2

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [74]:
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
# Stack tensors on top of each other
S_stacked = torch.stack([S2, S2, S2], dim=0)
S_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [76]:
# squeeze-> Returns a tensor with all specified dimensions of input of size 1 removed.
K = torch.zeros(2, 1, 2, 1, 2)

In [77]:
K

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [78]:
K.shape

torch.Size([2, 1, 2, 1, 2])

In [79]:
K.squeeze()

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [80]:
K.squeeze().shape

torch.Size([2, 2, 2])

In [81]:
# unsqueeze-> Returns a new tensor with a dimension of size one inserted at the specified position.
tensor_u = torch.tensor([19, 11, 12, 16, 2 ])

In [82]:
tensor_u.unsqueeze(dim=0), tensor_u.unsqueeze(dim=0).shape

(tensor([[19, 11, 12, 16,  2]]), torch.Size([1, 5]))

In [83]:
tensor_u.unsqueeze(dim=1), tensor_u.unsqueeze(dim=1).shape

(tensor([[19],
         [11],
         [12],
         [16],
         [ 2]]),
 torch.Size([5, 1]))

In [84]:
# permute-> Returns a view of the original tensor input with its dimensions permuted.
tensor_p = torch.rand(size=(32, 32, 3))
tensor_p.shape

torch.Size([32, 32, 3])

In [85]:
tensor_p.permute(2, 0, 1).shape

torch.Size([3, 32, 32])

In [86]:
tensor_p[0, 0, 0]

tensor(0.8522)

In [87]:
tensor_p.permute(2, 0, 1)[0, 0, 0]

tensor(0.8522)

### Tensor indexing

In [88]:
S = torch.arange(1, 10).reshape(1, 3, 3)
S, S.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [89]:
S[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [90]:
S[0][0]

tensor([1, 2, 3])

In [91]:
S[0][0][1]

tensor(2)

In [92]:
S[0, 2, 2]

tensor(9)

In [93]:
S[:, 0]

tensor([[1, 2, 3]])

In [94]:
S[:, :, 2]

tensor([[3, 6, 9]])

In [95]:
S[:, 1, 2]

tensor([6])

In [96]:
S[0, 1, :]

tensor([4, 5, 6])

### Pytorch tensors and Numpy

In [98]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
pytorch_array = torch.from_numpy(array)
array, pytorch_array

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [99]:
array.dtype

dtype('float64')

In [100]:
pytorch_array.dtype

torch.float64

In [101]:
array = array + 1
array, pytorch_array

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [102]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [103]:
tensor.dtype

torch.float32

In [104]:
numpy_tensor.dtype

dtype('float32')

### Reproducibility (trying to take random out of random)

In [105]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2469, 0.2632, 0.0023, 0.4973],
        [0.0484, 0.1718, 0.8177, 0.5063],
        [0.7182, 0.0404, 0.3571, 0.6563]])
tensor([[0.1273, 0.5107, 0.7480, 0.9303],
        [0.3174, 0.1987, 0.6289, 0.6429],
        [0.4202, 0.5633, 0.3987, 0.3443]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [106]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and pytorch objects on the gpus

In [107]:
torch.cuda.is_available()

True

In [108]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [109]:
torch.cuda.device_count()

1

In [110]:
tensor = torch.tensor([1, 2, 3])

In [111]:
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [112]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [113]:
tensor_back_on_cpu = tensor_on_gpu().numpy()
tensor_back_on_cpu

TypeError: 'Tensor' object is not callable

In [114]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)